### ISSUE TITLE
Forces to login again after F5 refresh

### ISSUE THREAD

**Issue by pbarone** [MausamGaurav/Streamlit_Multipage_AWSCognito_User_Authentication_Authorization#4]
The app works fine if I navigate across different pages but if I refresh by browser it forces me to re-authenticate even if the ?code=xxxx parameter is in the URL.

If I copy and paste the full URL to a new tab, it makes me authenticate again too

**Comment by MausamGaurav** [comment]
The auth code is valid only for one time. This is standard across most modern authentication systems. Reason being auth codes are mostly sent in redirect urls. Imagine somebody looked into your browser history and found the authcode? Hence it is valid only once. Since in streamlit we cannot use browser local storage etc., this method uses the auth code from the url parameter. And since the auth code is valid only for one usage the next time you try to authentictate with it, it won't work. A way around this is that you use the auth code to get a auth token and then encrypt the auth token and use that as a URL parameter.

**Comment by pbarone** [comment]
Isn’t it possible to store the auth token in the session?
